services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_uit
    ports:
      - '1433:1433'
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${SQL_PASSWORD}
    platform: linux/amd64
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data:
