USE BTTH2_DB;

-- PHẦN 2:
-- C. TRIGGER
-- 1. Tạo Trigger thỏa mãn điều kiện khi xóa một đề tài sẽ xóa các thông tin liên quan.
CREATE TRIGGER trg_DeleteDeTai
ON DETAI
INSTEAD OF DELETE
AS
    BEGIN
        DELETE FROM SV_DETAI WHERE MSDT IN (SELECT MSDT FROM DELETED);
        DELETE FROM GV_HDDT WHERE MSDT IN (SELECT MSDT FROM DELETED);
        DELETE FROM GV_PBDT WHERE MSDT IN (SELECT MSDT FROM DELETED);
        DELETE FROM GV_UVDT WHERE MSDT IN (SELECT MSDT FROM DELETED);
        DELETE FROM HOIDONG_DT WHERE MSDT IN (SELECT MSDT FROM DELETED);

        DELETE FROM DETAI WHERE MSDT IN (SELECT MSDT FROM DELETED);
    END
GO

