CREATE DATABASE BTTH2_DB
GO

CREATE TABLE SINHVIEN
(
    MSSV char(8) PRIMARY KEY,
    TENSV nvarchar(30) NOT NULL,
    SODT varchar(10),
    LOP  char(10) NOT NULL,
    DIACHI nchar(50) NOT NULL
)
GO

CREATE TABLE DETAI
(
    MSDT char(6) PRIMARY KEY,
    TENDT nvarchar(30) NOT NULL
)
GO

CREATE TABLE SV_DETAI
(
    MSSV char(8),
    MSDT char(6),
    PRIMARY KEY (MSSV, MSDT),
    FOREIGN KEY (MSSV) REFERENCES SINHVIEN(MSSV),
    FOREIGN KEY (MSDT) REFERENCES DETAI(MSDT)
)
GO

